name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    strategy:
      matrix:
        node: [10.22, 12.18, 14.13]
    # cypress workaround
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.node }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.CR_PAT }}

      # workaround for "No space left on device" action runner error
      - name: Free disk space
        run: |
          docker image prune -a -f >/dev/null 2>&1
          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
          sudo swapoff -a >/dev/null 2>&1
          sudo rm -f /swapfile >/dev/null 2>&1
          df -h

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ matrix.node }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/base:${{ matrix.node }}

          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
