name: Docker Image CI

on:
  push:
    branches: [master]
    paths:
      - "output/**"
      - ".github/workflows/docker-image.yml"

jobs:
  build_and_push:
    strategy:
      matrix:
        node: ["16.20", "18.16", "20.0"]
        distro: [debian, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # pin@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # pin@v1

      - name: Cache Docker layers
        uses: actions/cache@515d10b4fd9bb4858066bd5769f55bd498dcdd27 # pin@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.node }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-buildx-

      # workaround for "No space left on device" action runner error
      - name: Free disk space
        run: |
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get autoclean -y >/dev/null 2>&1
          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
          docker system prune --volumes -f >/dev/null 2>&1
          sudo swapoff -a >/dev/null 2>&1
          sudo rm -f /swapfile >/dev/null 2>&1
          df -h

      - name: Login to DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # pin@v1
        with:
          registry: ghcr.io
          username: synthetixio
          password: ${{ secrets.GH_PACKAGES_READ_WRITE }}

      - name: Build and push (${{ matrix.distro }}[${{ matrix.node }}])
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # pin@v2
        with:
          context: .
          file: ./output/${{ matrix.distro }}/${{ matrix.node }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/synthetixio/${{ github.event.repository.name }}/${{ matrix.distro }}:${{ matrix.node }}
            synthetixio/${{ github.event.repository.name }}:${{ matrix.node }}-${{ matrix.distro }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
